### PR TITLE
Handling boolean attributes properly

### LINKED ISSUE #119: Wrong boolean attributes conversion
**ERB Input:**
```erb
<input required>
```

**Output:**
```ruby
input(required: "")
```

**Expected output:**
```ruby
input(required: true)
```

### PR DESCRIPTION
**Pull request by stephannv**
Closes #119. 

Nokogiri #value is always returning "" to <input required> and <input required="">, so I have to call `#to_html` and check if the `=` character is present. I'm not sure if this is the best way, but I tried a lot of Nokogiri methods and none of them returns `nil`.

### CODE REVIEW

File: gem/lib/phlexing/template_generator.rb [hunk 1]
```diff
@@ -54,7 +54,7 @@ def handle_attributes(node)
 
       attributes = []
 
-      node.attributes.each_value do |attribute|
+      node.attribute_nodes.each do |attribute|
```
Comment (marcoroth) [inline gem/lib/phlexing/template_generator.rb:57]: TIL `attribute_nodes`! Thanks for this!

**Review by marcoroth — APPROVED** [review]
I think this is fair enough! Thanks for fixing this @stephannv!

**Comment by stephannv** [comment]
@marcoroth  I don't understand why the tests are broken, but I have to change the standalone head tag test to pass on local tests, should I push the changes?
Screen Shot 2023-03-28 at 15 06 13

**Comment by marcoroth** [comment]
I suspect it's because we are calling `to_html` on the attribute and that this is forcing that `<meta>` tag to generate within the `<head>` element

**Comment by marcoroth** [comment]
Yeah, seems like this is what is happening:
```ruby
irb(main):049:0> head = Nokogiri::HTML::Document.parse("<head id='123'>").css("head").first
=> #(Element:0x1e97cc { name = "head", attributes = [ #(Attr:0x1e9920 { name = "id", value = "123" })] })

irb(main):050:0> head.attribute_nodes
=> [#(Attr:0x1e9920 { name = "id", value = "123" })]

irb(main):051:0> head.attribute_nodes.first.to_html
=> " id=\"123\""

irb(main):053:0> head
=>
#(Element:0x1e97cc {
  name = "head",
  attributes = [ #(Attr:0x1e9920 { name = "id", value = "123" })],
  children = [
    #(Element:0x1f4514 {
      name = "meta",
      attributes = [ #(Attr:0x1f4668 { name = "http-equiv", value = "Content-Type" }), #(Attr:0x1f4848 { name = "content", value = "text/html; charset=UTF-8" })]
      })]
  })
```

**Comment by stephannv** [comment]
Now I'm making the `to_html` check only if the attribute value is blank instead of doing this to all attributes everytime.

**Comment by marcoroth** [comment]
> Now I'm making the `to_html` check only if the attribute value is blank instead of doing this to all attributes everytime.

Awesome, even better! Thank you!

**Comment by marcoroth** [comment]
This is now also running on https://phlexing.fun! 🎉

**Comment by stephannv** [comment]
Nice @marcoroth 👏🏼
Screen Shot 2023-03-28 at 20 29 43
